In [2]:
import matplotlib.pyplot as plt
import numpy as np
import csv
import us

In [3]:
elections = {}

In [4]:
with open("res/house_general_election_2016.csv") as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        if (row['state'] + row['fips']) not in elections:
            elections[(row['state']+row['fips'])] = {}
        #print(elections)
        if row['vote_pct'] == '':
            row['vote_pct'] = '100'
        
        if row['individual_party'] in elections[str(row['state']+row['fips'])]:
            elections[str(row['state']+row['fips'])][row['individual_party']] += float(row['vote_pct'])
        else:
            elections[str(row['state']+row['fips'])][row['individual_party']] = float(row['vote_pct'])

In [5]:
elections

{'Alabama1': {'republican': 100.0},
 'Alabama2': {'democrat': 45.4, 'republican': 54.6},
 'Alabama3': {'democrat': 32.9, 'republican': 67.1},
 'Alabama4': {'republican': 100.0},
 'Alabama5': {'democrat': 33.2, 'republican': 66.8},
 'Alabama6': {'democrat': 25.2, 'republican': 74.8},
 'Alabama7': {'democrat': 100.0},
 'Alaska1': {'democrat': 36.5,
  'independent_or_other': 13.0,
  'republican': 50.5},
 'Arizona1': {'democrat': 50.8,
  'independent_or_other': 5.7,
  'republican': 43.5},
 'Arizona2': {'democrat': 43.3, 'republican': 56.7},
 'Arizona3': {'democrat': 100.0},
 'Arizona4': {'democrat': 28.5, 'republican': 71.5},
 'Arizona5': {'democrat': 36.9, 'republican': 63.1},
 'Arizona6': {'democrat': 38.4, 'republican': 61.6},
 'Arizona7': {'democrat': 74.6, 'republican': 25.4},
 'Arizona8': {'independent_or_other': 31.4, 'republican': 68.6},
 'Arizona9': {'democrat': 61.1, 'republican': 38.9},
 'Arkansas1': {'independent_or_other': 23.5, 'republican': 76.5},
 'Arkansas2': {'democrat': 

In [6]:
for race in elections:
    #print(race)
    for key in ['republican', 'democrat', 'independent_or_other']:
        #print(key)
        if key not in elections[race]:
            elections[race][key] = 0
        elif elections[race][key] == '':
            elections[race][key] = 100
        else:
            elections[race][key] = float(elections[race][key])

In [7]:
elections

{'Alabama1': {'democrat': 0, 'independent_or_other': 0, 'republican': 100.0},
 'Alabama2': {'democrat': 45.4, 'independent_or_other': 0, 'republican': 54.6},
 'Alabama3': {'democrat': 32.9, 'independent_or_other': 0, 'republican': 67.1},
 'Alabama4': {'democrat': 0, 'independent_or_other': 0, 'republican': 100.0},
 'Alabama5': {'democrat': 33.2, 'independent_or_other': 0, 'republican': 66.8},
 'Alabama6': {'democrat': 25.2, 'independent_or_other': 0, 'republican': 74.8},
 'Alabama7': {'democrat': 100.0, 'independent_or_other': 0, 'republican': 0},
 'Alaska1': {'democrat': 36.5,
  'independent_or_other': 13.0,
  'republican': 50.5},
 'Arizona1': {'democrat': 50.8,
  'independent_or_other': 5.7,
  'republican': 43.5},
 'Arizona2': {'democrat': 43.3, 'independent_or_other': 0, 'republican': 56.7},
 'Arizona3': {'democrat': 100.0, 'independent_or_other': 0, 'republican': 0},
 'Arizona4': {'democrat': 28.5, 'independent_or_other': 0, 'republican': 71.5},
 'Arizona5': {'democrat': 36.9, 'ind

In [8]:
len(elections)

435

In [62]:
ea = np.zeros((435, 6))
e17 = {}
e17['Kansas4'] = {'republican':63505,'democrat':55310,'independent_or_other':2082}
e17['Georgia6'] = {'republican':98192,'democrat':94201,'independent_or_other':176}
e17['Montana1'] = {'republican':189473,'democrat':166483,'independent_or_other':21509}
e17['California34'] = {'republican':1089,'democrat':25581,'independent_or_other':1864}
for e in e17:
    e17[e]['margin'] = 100*(e17[e]['democrat']-e17[e]['republican'])/(e17[e]['republican']+e17[e]['democrat']+e17[e]['independent_or_other'])
el = []
for race in elections:
    #print(elections[race])
    r = [0, 0, 0, 0, 0]
    r[0] = elections[race]['republican']
    r[1] = elections[race]['democrat']
    r[2] = elections[race]['independent_or_other']
    r[3] = elections[race]['democrat'] - elections[race]['republican']
    if race in e17:
        r[4] = e17[race]['margin']#*100/(e17[race]['republican']+e17[race]['democrat']+e17[race]['independent_or_other'])
    #if 300000 not in r:
    el.append(r)
    
print(len(el))
print(np.asarray(el))


435
[[ 66.4  28.8   4.7 -37.6   0. ]
 [ 56.7  43.3   0.  -13.4   0. ]
 [ 61.5  34.3   4.2 -27.2   0. ]
 ..., 
 [ 72.9  27.1   0.  -45.8   0. ]
 [ 37.5  62.5   0.   25.    0. ]
 [ 61.1  32.5   6.4 -28.6   0. ]]


In [63]:
comps = []
for race in el:
    #print(race)
    if race[4] != 0:
        comps.append(race)
        
print(np.asarray(comps))

[[  61.6          38.4           0.          -23.2          -2.07250388]
 [  61.           29.4           9.6         -31.6          -6.7784974 ]
 [   0.          100.            0.          100.           85.83444312]
 [  56.3          40.5           3.2         -15.8          -6.09063092]]


In [58]:
from sklearn import linear_model

comps = np.asarray(comps)
print(comps)
print(comps[:,3])
print(comps[:,4])
reg = linear_model.LinearRegression(fit_intercept=False)
reg.fit(comps[:,3].reshape(-1,1), comps[:,4])
print(reg)


x_test = np.asarray(el)
#print(x_test)
y = reg.predict(x_test[:,3].reshape(-1,1))

results = np.c_[x_test[:,3], y]
print(results)
print(sum(results[:,4]))

[[ 61.6         38.4          0.         -23.2         -2.07250388]
 [ 61.          29.4          9.6        -31.6         -6.7784974 ]
 [ 56.3         40.5          3.2        -15.8         -6.09063092]]
[-23.2 -31.6 -15.8]
[-2.07250388 -6.7784974  -6.09063092]
LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)
[[ -37.6          -7.5458163 ]
 [ -13.4          -2.68920049]
 [ -27.2          -5.45867562]
 [ -14.           -2.80961245]
 [   7.6           1.52521819]
 [ -32.           -6.42197132]
 [ -15.4          -3.0905737 ]
 [ -38.           -7.62609094]
 [  19.4           3.89332011]
 [ -19.6          -3.93345743]
 [ -23.2          -4.65592921]
 [ -16.2          -3.25112298]
 [  80.4          16.13520294]
 [ -19.2          -3.85318279]
 [-100.          -20.06866037]
 [-100.          -20.06866037]
 [  22.            4.41510528]
 [  11.4           2.28782728]
 [  29.4           5.90018615]
 [ -90.          -18.06179434]
 [  23.7           4.75627251]
 [-100. 

IndexError: index 4 is out of bounds for axis 1 with size 2

In [54]:
#print(results)
changes = 0
old = 0
wins = 0
for r in results:
    changes += r[1]/435
    old += r[0]/435
    if r[1] > 48:
        wins += 1
print(changes)
print(old)
print(wins*100/435)

61.5945419206
48.9234482759
63.44827586206897
